# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Deploy to Firebase App Distribution"
  lane :firebase_distribution do
    firebase_app_distribution(
        app: '1:504251462470:ios:93532b483d1448a6eeeb47',
        release_notes_file: "Initial Release",
        testers: "amanikandan261194@gmail.com, leefordjudes@gmail.com",
    )
  end
end
