# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Deploy to Firebase App Distribution"
  lane :firebase_distribution do
    update_code_signing_settings(
  use_automatic_signing: true,
 )
    gym(scheme: "Runner")
    firebase_app_distribution(
      service_credentials_file: ENV['FIREBASE_CREDENTIALS'],
      app: ENV['FIREBASE_APP_ID'],
      release_notes_file: "Initial Release",
      testers: "amanikandan261194@gmail.com, leefordjudes@gmail.com",
      ipa:"./build/io.auditplus.mobile.ipa"
    )
  end
end
