# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Distribute to Firebase"
  lane :firebase_distribute do
    gradle(task: "assemble",build_type:"Release")
    firebase_app_distribution(
    app: "1:858564807264:android:fa393b9921bf01d7d0d105",
    testers: "amanikandan261194@gmail.com, leefordjudes@gmail.com",
  )
  end
end
