# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Distribute to Firebase"
  lane :firebase_distribute do
    gradle(task: "assemble",build_type:"Release", project_dir: 'android/')
    firebase_app_distribution(
    app: ENV['FIREBASE_ANDROID_APP_ID'],
    testers: "amanikandan261194@gmail.com, leefordjudes@gmail.com",
  )
  end
end
