# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Distribute APK to Firebase"

  lane :firebase_distribute do
    firebase_app_distribution(
    app: ENV['FIREBASE_ANDROID_APP_ID'],
    testers: "amanikandan261194@gmail.com, leefordjudes@gmail.com",
    apk_path:"../build/app/outputs/flutter-apk/app-release.apk",
    release_notes: "One Solution to manage all your business needs. Manage accounts, monitor your inventory, create invoices, receive payments, track your expenses, File GST return and grow your business with one single app.",
  )
  end
end
