name: Distribute APK To Firebase

on:
  workflow_dispatch:

jobs:
  release_ios:
    name: Distribute To Firebase
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Distribute app with Firebase
      run: |
            cd android
            fastlane firebase_distribute
      env:
          FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}} 
