name: IOSBuilder

on:
  workflow_dispatch:

jobs:
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Cache bundle dependencies
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-
    - name: Download bundle dependencies
      run: |
        gem install bundler:2.0.2
        bundle config path vendor/bundle
        bundle install
    - name: Create Firebase Service Credentials file
      run: |
          echo "$FIREBASE_CREDENTIALS" > GoogleService-Info.plist.b64
          base64 -d -i firebase_credentials.json.b64 > GoogleService-Info.plist.json
      env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
    - name: Distribute app with Firebase
      run: bundle exec fastlane distribute
      env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
