name: IOSBuilder

on:
  workflow_dispatch:

jobs:
  release_ios:
    name: Distribute To Firebase
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Cache bundle dependencies
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-
    - name: Install Bundle
      run: |
            gem install bundler:1.17.2
            bundle init
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3
    - name: Create Firebase Service Credentials file
      run: |
          echo "$FIREBASE_CREDENTIALS" > GoogleService-Info.plist.b64
          base64 -d -i GoogleService-Info.plist.b64 > GoogleService-Info.plist
      env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
    - name: Distribute app with Firebase
      run: bundle exec fastlane distribute
      env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
