name: Distribute To Firebase

on:
  workflow_dispatch:

jobs:
  release_ios:
    name: Distribute To Firebase
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Distribute app with Firebase
      run: |
            cd ios
            fastlane firebase_distribution
      env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}} 
          ipa_path: '/Users/runner/work/auditplus-mobile/auditplus-mobile/build/ios/iphoneos/Runner.ipa'
          

