name: Distribute To Firebase

on:
  workflow_dispatch:

jobs:
  release_ios:
    name: Distribute To Firebase
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
        bundler-cache: true 
    - name: Distribute app with Firebase
      run: |
            cd ios
            fastlane firebase_distribution

