name: IOSBuilder

on:
  workflow_dispatch:

jobs:
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Create Firebase Service Credentials file
      run: |
          echo "$FIREBASE_CREDENTIALS" > firebase_credentials.json.b64
          base64 -d -i firebase_credentials.json.b64 > firebase_credentials.json
      env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
    - name: Distribute app with Firebase
      run: bundle exec fastlane distribute
      env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
