name: IOSBuilder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - name: collect ipa artifacts
      uses: actions/upload-artifact@v2
      with:
        name: adhoc-ipa
        # Path to the release files
        path: /Users/runner/work/auditplus-mobile/auditplus-mobile/build/ios/iphoneos/Runner.app
