name: Distribute To Firebase

on:
  workflow_dispatch:

jobs:
  release_ios:
    name: Distribute To Firebase
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Create Firebase Service Credentials file
      run: |
          echo "$FIREBASE_CREDENTIALS" > GoogleService-Info.plist.b64
          base64 -d -i GoogleService-Info.plist.b64 > GoogleService-Info.plist
      env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
    - name: Distribute app with Firebase
      run: |
            cd ios && pod install
            bundle exec fastlane distribute
      env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
