name: Distribute To Firebase

on:
  workflow_dispatch:

jobs:
  release_ios:
    name: Distribute To Firebase
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.6'
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build ios --release --no-codesign
    - name: Install pods
      run: cd ios && pod install
    - name: Create Firebase Service Credentials file
      run: |
          echo "$FIREBASE_CREDENTIALS" > GoogleService-Info.plist.b64
          base64 -d -i GoogleService-Info.plist.b64 > GoogleService-Info.plist
      env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
    - name: Distribute app with Firebase
      run:  bundle exec fastlane distribute
      env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
