name: Distribute to firebase

on:
  workflow_dispatch:

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Deploy
        if: (github.base_ref == 'master' && github.event_name == 'pull_request')
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{secrets.FIREBASE_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          testers: "amanikandan261194@gmail.com, leefordjudes@gmail.com"
          release_notes: "a new version"
          file: ./build/Runner/Runner.ipa
